/*
 * exercise_4.c
 *
 *  Created on: Sep 20, 2024
 *      Author: HP
 */

#include "exercise_4.h"

//	@brief	Implement the 7-segment LED
//	@param	Integer number from 0 to 9
void display7SEG(int num) {
	switch(num) {
	case 0:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_SET);
		break;
	case 1:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_SET);
		break;
	case 2:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_RESET);
		break;
	case 3:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_RESET);
		break;
	case 4:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_RESET);
		break;
	case 5:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_RESET);
		break;
	case 6:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_RESET);
		break;
	case 7:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_SET);
		break;
	case 8:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_RESET);
		break;
	case 9:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_RESET);
		break;
	default:
		HAL_GPIO_WritePin(GPIOB, LED7_a1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_b1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_c1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_d1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_e1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_f1_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED7_g1_Pin, GPIO_PIN_SET);
		break;
	}
}

